
INSERT INTO USER (ID,USERNAME,PASSWORD,ENABLED) VALUES (1,'admin','password','true');
INSERT INTO USER (ID,USERNAME,PASSWORD,ENABLED) VALUES (2,'manager','password','true');
INSERT INTO USER (ID,USERNAME,PASSWORD,ENABLED) VALUES (3,'employee','password','true');

INSERT INTO USERROLE (ID,ROLE,USER) VALUES(1, 'Admin',1);
INSERT INTO USERROLE (ID,ROLE,USER) VALUES(2, 'Employee',1);

INSERT INTO USERROLE (ID,ROLE,USER_ID) VALUES(3, 'Manager',2);
INSERT INTO USERROLE (ID,ROLE,USER) VALUES(4, 'Employee',2);

INSERT INTO USERROLE (ID,ROLE,USER) VALUES(5, 'Employee',3);