INSERT INTO USERROLE (ID,ROLE) VALUES(1, 'Admin');
INSERT INTO USERROLE (ID,ROLE) VALUES(2, 'Manager');
INSERT INTO USERROLE (ID,ROLE) VALUES(3, 'Employee');

INSERT INTO USER (USERNAME,PASSWORD,ENABLED,USERROLE) VALUES ('admin','password','true',1);
INSERT INTO USER (USERNAME,PASSWORD,ENABLED,USERROLE) VALUES ('manager','password','true',2);
INSERT INTO USER (USERNAME,PASSWORD,ENABLED,USERROLE) VALUES ('employee','password','true',3);